# Generated by Django 4.1 on 2023-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_plant_pot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefindedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("moisture", models.IntegerField()),
            ],
        ),
    ]
