# Generated by Django 4.1 on 2023-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_plant_pot", "0002_defindedstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=255)),
            ],
        ),
    ]
